version: '3.1'
services:
  php:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    volumes:
      - './app:/var/www/html'
      - './docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
      - './docker/php-ini:/usr/local/etc/php/custom.d'
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'php'
    volumes:
      - './app:/var/www/html'
      - './config/nginx:/etc/nginx/conf.d'

  mariadb:
    image: mariadb:10.3.9
    restart: 'on-failure'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpass
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'

  localstack:
    image: localstack/localstack
    container_name: awslocal
    hostname: awslocal
    environment:
      EDGE_PORT: 4566
      DEFAULT_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar

      DOCKER_HOST: unix:///var/run/docker.sock
      HOST_TMP_FOLDER: /tmp/localstack
      HOSTNAME_EXTERNAL: awslocal
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"